sudo: required

#cache:
#  directories:
#    - node_modules # cache node_module

addons:
  chrome: stable

language: node_js

node_js:
- "10"

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng build --prod
#- ng test

after_success:
  - firebase use --token ${FIREBASE_TOKEN} # set firebase token
  - firebase use --add ${PROJECT_ID} # set current project
  - firebase deploy --non-interactive --token "${FIREBASE_TOKEN}"

# deploy project
#deploy:
#  provider: firebase
#  api_key:
#    secure: "YOUR ENCRYPTED API KEY"